### ISSUE TITLE
Sorting order is preserved from projects page to home page

### ISSUE THREAD

**Issue by Qrtn** [SirajChokshi/portfolio#1]
![image](https://user-images.githubusercontent.com/4369024/120437490-bd3d4100-c345-11eb-8aaf-b435ffa8085e.png)

**Comment by code-arman** [comment]
Clever Girl 🦖😗 
![](https://user-images.githubusercontent.com/19193347/119385320-f87ba800-bc93-11eb-85f6-e590a5b32879.gif)
